blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("post/<int:pk>/", views.blog_detail, name="blog_detail"),
    path("category/<category>", views.blog_category, name="blog_category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("blog/", include("blog.urls", namespace="blog")),
]

core/urls.py
from django.urls import path

app_name = "core"

urlpatterns = []

blog/models.py
from django.db import models
from core.models import User


class Category(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return str(self.name)
  

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField("Category", related_name="posts")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ["-created_on"]
    
    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.author} on {self.post}"

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Leave a comment...",
            }
        )
    )
    

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Post, Comment
from .forms import CommentForm


def blog_index(request):
    posts = Post.objects.all()
    context = {
        "posts": posts,
    }
    return render(request, "blog/index.html", context)


def blog_category(request, category):
    posts = Post.objects.filter(categories__name__contains=category)
    context = {
        "category": category,
        "posts": posts,
    }
    return render(request, "blog/category.html", context)


def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                body=form.cleaned_data["body"],
                post=post,
                author=request.user
            )
            comment.save()
            return HttpResponseRedirect(request.path_info)
    
    comments = Comment.objects.filter(post=post)
    context = {
        "comments": comments,
        "form": form,
        "post": post,
    }
    return render(request, "blog/detail.html", context)

core/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/category.html
{% extends "blog/index.html" %}

{% block page_title %}
    <h2>{{ category }}</h2>
{% endblock page_title %}

blog/templates/blog/detail.html
{% extends "base.html" %}

{% block page_title %}
    <h2>{{ post.title }}</h2>
{% endblock page_title %}

{% block page_content %}
    <small>
        {{ post.created_on.date }} | Categories:
        {% for category in post.categories.all %}
            <a href="{% url 'blog:blog_category' category.name %}">
                {{ category.name }}
            </a>
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>

    {% if user.is_authenticated %}
    <h3>Leave a comment:</h3>
    <form method="post">
        {% csrf_token %}
        <div>
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% else %}
        <h3> Please login to leave a comment </h3>
    {% endif %}

    <h3>Comments:</h3>
    {% for comment in comments %}
        <p>
            On {{ comment.created_on.date }} <b>{{ comment.author.first_name }}</b> wrote:
        </p>
        <p>
            {{ comment.body | linebreaks }}
        </p>
    {% endfor %}
{% endblock page_content %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block page_title %}
    <h2>Blog Posts</h2>
{% endblock page_title %}

{% block page_content %}
    {% block posts %}
        {% for post in posts %}
            <h3><a href="{% url 'blog:blog_detail' post.pk %}">{{ post.title }}</a></h3>
            <small>
                {{ post.created_on.date }} | Categories:
                {% for category in post.categories.all %}
                    <a href="{% url 'blog:blog_category' category.name %}">
                        {{ category.name }}
                    </a>
                {% endfor %}
            </small>
            <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    {% endblock posts %}
{% endblock page_content %}

templates/base.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>The Blog of All Blogs</title>
        <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    </head>
    <body>
        <h1>The Blog of All Blogs</h1>
        <a href="{% url 'blog:blog_index' %}">Home</a>
    <hr>
        {% block page_title %}{% endblock page_title %}
        {% block page_content %}{% endblock page_content %}
    </body>
    </html>